config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  delete '/shops', to: 'shops#destroy'
  root to: 'shops#home'
  resources :shops do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :new]
  end

  resources :accounts
  resources :comments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :username, presence: true 
  validates :profile, length: { maximum: 200 } 
  has_many :shops, dependent: :destroy
  has_many :favorites
  has_many :favorite_shops, through: :favorites, source: :shop
  has_many :comments
  mount_uploader :image, ImageUploader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: {maximum: 120}

  belongs_to :account
  belongs_to :shop
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :account
    belongs_to :shop
    validates_uniqueness_of :shop_id, scope: :account_id
end

app/models/shop.rb
class Shop < ApplicationRecord
  validates :name, presence: true, length: {maximum: 30}
  validates :recommended, presence: true
  validates :prefecture_id, presence: true
  validates :open_at, presence: true
  validates :close_at, presence: true
  validates :description, length: {maximum: 300}

  has_one_attached :image
  belongs_to :account
  has_many :favorites
  has_many :comments, dependent: :destroy
  mount_uploader :image, ImageUploader

  geocoded_by :city
  after_validation :geocode, if: :city_changed?

  enum prefecture_id: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }
  enum holiday_id: {
    日曜日:1,月曜日:2,火曜日:3,水曜日:4,木曜日:5,金曜日:6,土曜日:7,不定休:8
  }

  scope :search, -> (search_params) do
    return if search_params.blank?

    name_like(search_params[:name])
      .prefecture_id_is(search_params[:prefecture_id])
  end
  scope :name_like, -> (name){where('name LIKE ?', "%#{name}%") if name.present?}
  scope :prefecture_id_is, -> (prefecture_id){where(prefecture_id: prefecture_id) if prefecture_id.present?}

  def favorited_by?(account)
    favorites.where(account_id: account.id).exists?
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
  end

  def show
    @account = Account.find(params[:id])
    @shops = @account.shops
    @comments = @account.comments.page(params[:page]).per(5)
    @favorite_shops = @account.favorite_shops

    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      added_attrs = [ :email, :username, :password, :password_confirmation, :profile, :image ]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
      devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    end


    private

    def current_user
      @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_account!        
    def new
        if account_signed_in?
            @comment = current_account.comments.new
        end
    end   

    def create
        @comment = current_account.comments.new(comment_params)
        @comment.shop_id = params[:shop_id]
        if @comment.save
            redirect_back fallback_location: root_url, notice:"コメントが投稿されました。"
        else
            redirect_back fallback_location: root_url, notice:"コメントが失敗しました。"
        end

    end 

    def destroy
        current_account.comments.find_by(id: params[:id]).destroy
        redirect_back fallback_location: root_url, notice:"コメントを削除しました。"
    end    

    private
    def comment_params
        params.require(:comment).permit(:content, :recommended, :shop_id, :image, :bitterness, :acidity, :fragrance, :rich, :sweetness)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_account!

  def create
    @shop = Shop.find(params[:shop_id])
    favorite = current_account.favorites.build(shop_id: params[:shop_id])
    favorite.save!
  end

  def destroy
    @shop = Shop.find(params[:shop_id])
    favorite = Favorite.find_by(shop_id: params[:shop_id], account_id: current_account.id)
    favorite.destroy
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_account!, only: [:new, :edit, :destroy]

  def index
    @search_params = shop_search_params
    @search_shops = Shop.search(@search_params).order(created_at: :desc).page(params[:page])
    @shops = Shop.all.order(created_at: :desc).page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @shop = Shop.find(params[:id])
    gon.shop_recommended = @shop.recommended
    gon.shop_bitterness = @shop.bitterness
    gon.shop_acidity = @shop.acidity
    gon.shop_fragrance = @shop.fragrance
    gon.shop_rich = @shop.rich
    gon.shop_sweetness = @shop.sweetness
    gon.shop_latitude = @shop.latitude
    gon.shop_longitude = @shop.longitude
    @comments = @shop.comments.order(created_at: :desc).page(params[:page]).per(5)

    if account_signed_in?
      @comment = current_account.comments.new
    end
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    @shop.account_id = current_account.id
    if @shop.save
      redirect_to shops_url, notice: "カフェ「#{@shop.name}」を登録しました！"
    else
      render 'new'
    end
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def update
    @shop = Shop.find(params[:id])
    if @shop.update(shop_params)
      redirect_to shops_url, notice: "カフェ「#{@shop.name}」を更新しました。"
    else
      render 'edit'
    end
  end

  def destroy
    shop = Shop.find(params[:id])
    shop.destroy
    redirect_to shops_url notice: "カフェ「#{shop.name}」の投稿を削除しました。"
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :recommended, :prefecture_id, :city, :bitterness, :acidity, :fragrance, :rich, :sweetness, :address, :description, :image, :open_at, :close_at, :station, :holiday_id, :phone_number, :latitude, :longitude)
  end

  def login_required
    redirect_to login_url unless current_user
  end

  def shop_search_params
    params.fetch(:search, {}).permit(:name,:prefecture_id)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
    def bootstrap_devise_error_messages!
      return "" if resource.errors.empty?
  
      html = ""
      resource.errors.full_messages.each do |error_message|
        html += <<-EOF
        <div class="alert alert-danger alert-dismissible" role="alert">
            <a class="close" data-dismiss="alert">×</a>
            #{error_message}
        </div>
        EOF
      end
      html.html_safe
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/accounts/_comments_page.html.slim
.container
  h3.mt-3.mb-5 コメント一覧
  - if @comments.any?
    - @comments.each do |comment|  
      .container.center-block.mb-2
        .card.my-2 style=("width: 100%; height: 210px;") 
          .card-header
            span.card-link #{link_to comment.shop.name, shop_url(comment.shop_id)}
            span.card-link
              - if account_signed_in? && current_account.id == comment.account_id 
                = link_to 'コメント削除' ,comment ,method: :delete, data: { confirm: "コメントを削除します。よろしいですか？"}, class: 'btn btn-outline-secondary btn-sm'

          .card-body
            - if comment.recommended.present?
              .card-text
                span おすすめ
                span.badge.badge-secondary #{comment.recommended}
            p.content-text 
              = comment.content

          p.card-text.text-muted.text-right.mr-2.mb-2.content-text  #{time_ago_in_words(comment.created_at)} 前
    = paginate @comments, remote: true 

app/views/accounts/show.html.slim
= form_with model: @account, local: true do |f|

.container
  h3.mt-3.mb-5 #{@account.username}さんのページ

.container.my-3.text-center
  - if @account.image?
    td= image_tag @account.image.thumb.url, class: "my-3 img-fluid rounded-circle account-image"
  - else
    td= image_tag "account", class: "my-3 img-fluid rounded-circle account-image" 
.container.w-75
  table.table
    tbody
      tr
        th = Account.human_attribute_name(:username)
      tr
        td = @account.username
      tr
        th = Account.human_attribute_name(:profile)
      tr
        td =  @account.profile

.container
  h5.mt-3.mb-5 #{@account.username}さんの投稿
  - if @shops.any?
    .row.my-3.mx-3
      - @shops.each do |shop|
        .col-lg-4.col-sm-6
          .card.mb-3
            .bd-placeholder-img.card-img-top
              = link_to shop_url(shop), class: "shop-card-link" do
                - if shop.image.thumb.url
                  = image_tag shop.image.thumb.url, class:"img-fluid mx-auto d-block shop-thumbnail" 
                - else
                  = image_tag "coffee", class:"img-fluid mx-auto d-block shop-thumbnail" 

            .card-body
              p.card-title = link_to shop.name, shop_url(shop), class: "text-dark"
              .row
                card-title.fa.fa-heart.like-btn
                ml-1 #{shop.favorites.count}
                card-title.fa.fa-comment.ml-2.mr-1.comment-btn
                mr-3 #{shop.comments.count}
  - else
    p 投稿したカフェはありません

.container
  h5.mt-3.mb-5 いいね！したカフェ
  - if @favorite_shops.any?
    .row.my-3.mx-3
      - @favorite_shops.each do |shop|
        .col-lg-4.col-sm-6
          .card.mb-3
            .bd-placeholder-img.card-img-top
              = link_to shop_url(shop), class: "shop-card-link" do
                - if shop.image.thumb.url
                  = image_tag shop.image.thumb.url, class:"img-fluid mx-auto d-block shop-thumbnail" 
                - else
                  = image_tag "coffee", class:"img-fluid mx-auto d-block shop-thumbnail" 

            .card-body
              p.card-title = link_to shop.name, shop_url(shop), class: "text-dark"
              .row
                card-title.fa.fa-heart.like-btn
                ml-1 #{shop.favorites.count}
                card-title.fa.fa-comment.ml-2.mr-1.comment-btn
                mr-3 #{shop.comments.count}
  - else
    p いいね!したカフェはありません

#comments_page
  .container
    h5.mt-3.mb-5 コメント一覧
    - if @comments.any?
      - @comments.each do |comment|  
        .container.center-block.mb-2
          .card.my-2 style=("width: 100%; height: 210px;") 
            .card-header
              span.card-link #{link_to comment.shop.name, shop_url(comment.shop_id)}
              span.card-link
                - if account_signed_in? && current_account.id == comment.account_id 
                  = link_to 'コメント削除' ,comment ,method: :delete, data: { confirm: "コメントを削除します。よろしいですか？"}, class: 'btn btn-outline-secondary btn-sm'

            .card-body
              - if comment.recommended.present?
                .card-text
                  span おすすめ
                  span.badge.badge-secondary #{comment.recommended}
              p.content-text 
                = comment.content

            p.card-text.text-muted.text-right.mr-2.mb-2.content-text  #{time_ago_in_words(comment.created_at)} 前
      = paginate @comments, remote: true

    - else
      p コメントしたカフェはありません

app/views/accounts/show.js.erb
$('#comments_page').html("<%= escape_javascript(render 'comments_page') %>");

app/views/favorites/_favorite.html.slim
  - if account_signed_in?
    -if shop.favorited_by?(current_account)
      p.text-right.my-3
        = link_to shop_favorites_path(shop.id), method: :delete, remote: true
          i.fa.fa-heart.unlike-btn
          span
            = shop.favorites.count
    -else
      p.text-right.my-3
        = link_to shop_favorites_path(shop.id), method: :post, remote: true
          i.far.fa-heart.like-btn 
          span
            = shop.favorites.count
        
  -else
    p.text-right.my-3
      span.fa.fa-heart.unlike-btn
      = shop.favorites.count

app/views/layouts/application.html.slim
doctype html
html lang="ja"
  head
    title
      | Cafeshira
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = include_gon
    = favicon_link_tag 'favi_cafe.png'
    meta content="width=device-width, initial-scale=1" name="viewport" /
    script src="https://kit.fontawesome.com/10ad47674d.js" crossorigin="anonymous"
    link href="https://fonts.gstatic.com" rel="preconnect" /
    link href="https://fonts.googleapis.com/css2?family=Courgette&display=swap" rel="stylesheet" /
  body
    .app-title.navbar.navbar-expand-md.navbar-dark.bg-dark.sticky-top
      .navbar-brand 
        = link_to "Cafeshira", root_url, class: "navbar-brand mr-4" 

      button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbar-content" 
        span.navbar-toggler-icon
      .collapse.navbar-collapse#navbar-content
        ul.navbar-nav.ml-auto
          - if account_signed_in?
            li.nav-item = link_to 'ホーム', root_url, class: 'nav-link'
            li.nav-item = link_to '店舗一覧', shops_path, class: 'nav-link'
            li.nav-item = link_to 'カフェ投稿', new_shop_path, class: 'nav-link'
            li.nav-item.dropdown.mr-5
              = link_to "アカウント", '#', 'data-toggle': 'dropdown', class: "nav-link dropdown-toggle"
              .dropdown-menu
                = link_to 'マイページ', account_url(current_account), class: "dropdown-item"
                = link_to 'アカウント編集', edit_account_registration_path, class: "dropdown-item"
                = link_to 'ログアウト', destroy_account_session_path, method: :delete, class: "dropdown-item"
          -  else
            li.nav-item = link_to 'ホーム', root_url, class: 'nav-link'
            li.nav-item= link_to '店舗一覧', shops_path, class: 'nav-link'
            li.nav-item= link_to '新規登録', new_account_registration_path, class: 'nav-link'
            li.nav-item= link_to 'ログイン', new_account_session_path, class: 'nav-link'

    = yield

app/views/shops/_comments.html.slim
.container.w-75.my-3
  - if account_signed_in?
    p
      button.btn.btn-outline-primary.btn-block.mx-auto aria-controls="collapseExample" aria-expanded="false" data-target="#collapseExample" data-toggle="collapse" type="button" 
        | コメントする
    #collapseExample.collapse
      = form_with model:[@shop, @comment], method: :post, local: true do |f|
        .form-group
          = f.label :content, class: 'control-label'
          span.badge.badge-secondary 120文字以内
          = f.text_area :content, class: 'form-control'
          = f.hidden_field :shop_id, value: @shop.id
        .form-group
          = f.label :recommended, class: 'control-label'
          = f.text_field :recommended, class: 'form-control', id: 'shop_recommended'
          = f.hidden_field :shop_id, value: @shop.id 
        = f.submit '投稿する',class: 'btn btn-outline-info d-block mx-auto'
  - else
    .row.w-75.d-block.mx-auto
      .col-md-6.col-md-offset-3.mx-auto.d-block
         = link_to 'ログインしてコメントする', new_account_session_url, class: 'btn btn-outline-info d-block mx-auto'

#comments_page
  .container.mb-5
    p コメント一覧
    - if @comments.any?
      - @comments.each do |comment|  
        .container.center-block.mb-2
          .card.my-2 style=("width: 100%; height: 210px;") 
            .card-header
              span.card-link 投稿者:#{link_to comment.account.username, account_path(comment.account.id)}さん
              span.card-link.text-right
                - if account_signed_in? && current_account.id == comment.account_id 
                  = link_to 'コメント削除' ,comment ,method: :delete, data: { confirm: "コメントを削除します。よろしいですか？"}, class: 'btn btn-outline-secondary btn-sm'

            .card-body.px-2.py-2
              - if comment.recommended.present?
                .card-text
                  span おすすめ
                  span.badge.badge-secondary #{comment.recommended}
              p.content-text
                = comment.content

            p.card-text.text-muted.text-right.mr-2.mb-2.content-text  #{time_ago_in_words(comment.created_at)} 前
      = paginate @comments, remote: true
    - else 
     p コメントはありません       

    

app/views/shops/_comments_page.html.slim
.container.mb-5
  p コメント一覧
  - if @comments.any?
    - @comments.each do |comment|  
      .container.center-block.mb-2
        .card.my-2 style=("width: 100%; height: 210px;") 
          .card-header
            span.card-link 投稿者:#{link_to comment.account.username, account_path(comment.account.id)}さん
            span.card-link.text-right
              - if account_signed_in? && current_account.id == comment.account_id 
                = link_to 'コメント削除' ,comment ,method: :delete, data: { confirm: "コメントを削除します。よろしいですか？"}, class: 'btn btn-outline-secondary btn-sm'
          .card-body
            - if comment.recommended.present?
              .card-text.px-2.py-2
                span おすすめ
                span.badge.badge-secondary #{comment.recommended}
            p.content-text
              = comment.content
          p.card-text.text-muted.text-right.mr-2.mb-2.content-text  #{time_ago_in_words(comment.created_at)} 前
    = paginate @comments, remote: true
  - else 
   p コメントはありません      

app/views/shops/_index_page.html.slim
.container
  - if @search_params.blank?
    .row.my-3.mx-3
      - @shops.each do |shop|
        .col-lg-4.col-sm-6
          .card.mb-3
            .bd-placeholder-img.card-img-top
              = link_to shop_url(shop), class: "shop-card-link" do
                - if shop.image.thumb.url
                  = image_tag shop.image.thumb.url, class:"img-fluid mx-auto d-block shop-thumbnail" 
                - else
                  = image_tag "coffee", class:"img-fluid mx-auto d-block shop-thumbnail" 

            .card-body
              p.card-title = link_to shop.name, shop_url(shop), class: "text-dark"
              .row
                card-title.fa.fa-heart.like-btn
                ml-1 #{shop.favorites.count}
                card-title.fa.fa-comment.ml-2.mr-1.comment-btn
                mr-3 #{shop.comments.count}
    = paginate @shops, remote: true
  - else
    - if @search_shops.blank?
        p.text-center.py-3 一致する検索結果がありません。
    - else
      .row.my-3.mx-3
        - @search_shops.each do |shop|
          .col-lg-4.col-sm-6
            .card.mb-3
              .bd-placeholder-img.card-img-top
                = link_to shop_url(shop), class: "shop-card-link" do
                  - if shop.image.thumb.url
                    = image_tag shop.image.thumb.url, class:"img-fluid mx-auto d-block shop-thumbnail" 
                  - else
                    = image_tag "coffee", class:"img-fluid mx-auto d-block shop-thumbnail" 
              .card-body
                p.card-title = link_to shop.name, shop_url(shop), class: "text-dark"
                .row
                  card-title.fa.fa-heart.like-btn
                  ml-1 #{shop.favorites.count}
                  card-title.fa.fa-comment.ml-2.mr-1.comment-btn
                  mr-3 #{shop.comments.count}
      = paginate @search_shops, remote: true

app/views/shops/_info.html.slim
.container
  - if shop.image.thumb.url
    img.text-center = image_tag shop.image.thumb.url, class: "my-3 img-fluid d-block mx-auto shop-image"
  - else
    img.text-center = image_tag "no_image", class: "my-3 img-fluid d-block mx-auto shop-image"

.container
  table.table.table-hover style="table-layout:fixed;"
    tbody
      tr
        th.text-center style="width:100px;"
          = Shop.human_attribute_name('投稿者')
        td = link_to shop.account.username, account_path(shop.account.id)
      tr 
       th.text-center = Shop.human_attribute_name(:prefecture_id)
       td= shop.prefecture_id
      tr 
       th.text-center = Shop.human_attribute_name(:city)
       td= shop.city
      tr 
       th.text-center = Shop.human_attribute_name(:station)
       td= shop.station
      tr 
       th.text-center = Shop.human_attribute_name(:open_at)
       td= shop.open_at.strftime("%H:%M")
      tr 
       th.text-center = Shop.human_attribute_name(:close_at)
       td= shop.close_at.strftime("%H:%M")
      tr 
       th.text-center = Shop.human_attribute_name(:holiday_id)
       td= shop.holiday_id
      tr 
       th.text-center = Shop.human_attribute_name(:phone_number)
       td= link_to shop.phone_number, "tel:#{shop.phone_number}"
      tr 
       th.text-center = Shop.human_attribute_name(:recommended)
       td= shop.recommended
      tr
       th.text-center = Shop.human_attribute_name(:description)
       td= simple_format(h(shop.description), {}, sanitize: false, wrapper_tag: "div")
      - if shop.prefecture_id
        tr
          th.text-center = Shop.human_attribute_name('アクセス')
          td.embeded-responsive.embeded-responsive-4by3.text-center       
            = render partial: 'map', locals: { shop: shop}
            
.container-fluid
  h5.text-center #{shop.recommended}の特徴
  = render partial: 'chart', locals: { shop: shop}

app/views/shops/_search_form.html.slim
= form_with  url: shops_path, scope: :search, method: :get, local: true do |f|
  .container.w-80
    .row.border.rounded.search-container
      .form-group.col-md-4.col-sm-6
        = f.label :店名, class: 'col-form-label text-muted'
        = f.text_field :name, value: @search_params[:name], class: 'form-control', id: 'shop_name'
      .form-group.col-md-4.col-sm-6
        = f.label :エリア, class: 'col-form-label text-muted'
        = f.select :prefecture_id, Shop.prefecture_ids.keys, {prompt: '選択してください'}, class: 'form-control' 
      .form-group.col-md-4.col-sm-4
        .search-btn
          = button_tag type: 'submit', class:"btn btn-outline-secondary btn-block mx-auto"
            | 検索する
            i.fas.fa-search
          

app/views/shops/home.html.slim
.home-background
  .jumbotron.jumbotron-fluid.mb-0
    .container
      - if flash.notice.present?
        - flash.each do |msg_type, msg|
          #alert class=("alert alert-#{msg_type}") role="alert" 
            = msg
    .container-fluid
      .home-title
        h1.display-3 Cafeshira
        p.lead コーヒーマニアのためのサイト。
        - if account_signed_in?
          = link_to "投稿を見る", shops_path, class: 'btn btn-outline-info w-15 my-2 my-sm-0'
        - else        
          = link_to "ログイン", new_account_session_path, class: 'btn btn-outline-info w-15 my-2 my-sm-0'

app/views/shops/index.html.slim
.container
  - if flash.notice.present?
    - flash.each do |msg_type, msg|
      #alert class=("alert alert-#{msg_type}") role="alert" 
        = msg
.container
  h3.my-4 店舗一覧
= render partial: 'search_form', locals: {shop: @shop}
#index_page
  .container
    - if @search_params.blank?
      .row.my-3.mx-3
        - @shops.each do |shop|
          .col-lg-4.col-sm-6
            .card.mb-3
              .bd-placeholder-img.card-img-top
                = link_to shop_url(shop), class: "shop-card-link" do
                  - if shop.image.thumb.url
                    = image_tag shop.image.thumb.url, class:"img-fluid mx-auto d-block shop-thumbnail" 
                  - else
                    = image_tag "no_image", class:"img-fluid d-block no-thumbnail " 

              .card-body
                p3.card-title = link_to shop.name, shop_url(shop), class: "text-dark"
                .row
                  card-text.fa.fa-heart.like-btn
                  ml-1 #{shop.favorites.count}
                  card-text.fa.fa-comment.ml-2.mr-1.comment-btn
                  mr-3 #{shop.comments.count}
      = paginate @shops, remote: true


    - else
      - if @search_shops.blank?
          p.text-center.py-3 一致する検索結果がありません。
      - else
        .row.my-3.mx-3
          - @search_shops.each do |shop|
            .col-lg-4.col-sm-6
              .card.mb-3
                .bd-placeholder-img.card-img-top
                  = link_to shop_url(shop), class: "shop-card-link" do
                    - if shop.image.thumb.url
                      = image_tag shop.image.thumb.url, class:"img-fluid mx-auto d-block shop-thumbnail" 
                    - else
                      = image_tag "coffee", class:"img-fluid mx-auto d-block shop-thumbnail" 
                .card-body
                  p3.card-title = link_to shop.name, shop_url(shop), class: "text-dark"
                  .row
                    card-text.fa.fa-heart.like-btn
                    ml-1 #{shop.favorites.count}
                    card-text.fa.fa-comment.ml-2.mr-1.comment-btn
                    mr-3 #{shop.comments.count}
        = paginate @search_shops, remote: true
.container
  - if account_signed_in?
    .row.w-75.d-block.mx-auto
      .col-md-6.col-md-offset-3.mx-auto.d-block
         = link_to 'カフェを投稿', new_shop_path, class: "btn btn-outline-info btn-lg my-5 w-100"

  - else
    .row.w-75.d-block.mx-auto
      .col-md-6.col-md-offset-3.mx-auto.d-block
          = link_to 'ログインしてカフェを投稿する', new_account_session_url, class: "btn btn-outline-info btn-lg my-5 w-100"






      

        
    
 
        

        
 

        

app/views/shops/show.html.slim
.container
    - if flash.notice.present?
      - flash.each do |msg_type, msg|
        #alert class=("alert alert-#{msg_type}") role="alert" 
          = msg

.container
  h3.text-center.my-4 #{@shop.name}
  .container.w-75
    div id="favorites_buttons_#{@shop.id}"
      = render partial: 'favorites/favorite', locals: { shop: @shop}

  .nav.justify-content-end
    = link_to '一覧へ戻る', shops_path, class: 'btn btn-outline-secondary my-2 my-sm-0'

= render partial: 'info', locals: {shop: @shop}

.container.w-75
  - if account_signed_in? && current_account.id == @shop.account_id 
    = link_to '編集' ,edit_shop_path, class: 'btn btn-block mx-auto btn-outline-info my-3'
    = link_to '削除' ,@shop ,method: :delete, data: { confirm: "「#{@shop.name}」を削除します。よろしいですか？"}, class: 'btn btn-block btn-outline-secondary my-3'

= render partial: 'comments'